### ISSUE TITLE
Provide the option for custom return url on plugin configuration

### ISSUE THREAD

**Issue by alexbogias** [ellak-monades-aristeias/Woocommerce-Payment-Gateways-Greek-Banks#1]
While I selected thank you page as the return url on your plugin configuration page my customer returns to /checkout page (for example /checkout?key=wc_order_585425eca911&order=7911) and not /checkout/order-received url like the rest payment options. Can you please fix it or give us the option so we can provide our custom return url on the configuration page. I dont see any other option on the pages dropdown.

**Comment by bekatoros** [comment]
This is because Piraeus demands a single url for checkout. So the parameter implementation, though deprecated was the only option for creating a single url. A user has suggested an improvement in Wordpress forum, but I will not implement it. Feel free to try it and if it works please make a pull request.

**Comment by alexbogias** [comment]
Thanks a lot for your answer Marios but i wasnt talking about the parameter. I just want to add /checkout/order-received but i can only get pages like /checkout /cart and self created pages on the list. If i had the option to manual enter the url, it should be great.
